var k;k||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),m=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://"),p,q,qa,ra,r,v,w,sa,ta;
function ua(){var a=va.buffer;p=new Int8Array(a);qa=new Int16Array(a);q=new Uint8Array(a);ra=new Uint16Array(a);r=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);sa=new Float64Array(a);ta=new BigInt64Array(a);new BigUint64Array(a)}function y(a){k.onAbort?.(a);a="Aborted("+a+")";m(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var wa;
async function xa(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==wa&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ya(a,b){try{var c=await xa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),y(d)}}
async function za(a){var b=wa;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return ya(b,a)}class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ba=a=>{for(;0<a.length;)a.shift()(k)},Ca=[],Da=[],Ea=()=>{var a=k.preRun.shift();Da.push(a)},Fa=0,Ga=null,Ha=()=>{Fa--;k.monitorRunDependencies?.(Fa);if(0==Fa&&Ga){var a=Ga;Ga=null;a()}},Ia=()=>{Fa++;k.monitorRunDependencies?.(Fa)},Ja=!0,Ka=[],La=0,Na=0;class Oa{constructor(a){this.Ld=a;this.wc=a-24}}
var Ra=a=>{var b=Na;if(!b)return Pa(0),0;var c=new Oa(b);v[c.wc+16>>2]=b;var d=v[c.wc+4>>2];if(!d)return Pa(0),b;for(var e of a){if(0===e||e===d)break;if(Qa(e,d,c.wc+16))return Pa(e),b}Pa(d);return b},Ta=()=>{var a=r[+Sa>>2];Sa+=4;return a},Ua=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Va=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ua(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Wa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Xa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Ya=a=>{(Ya=Xa())(a)},Za=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";
b=c+"/"+b;c="/"===c.charAt(0)}b=Ua(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},$a=globalThis.TextDecoder&&new TextDecoder,z=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&$a)return $a.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},ab=[],bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},A=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;
b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},cb=a=>{var b=Array(bb(a)+1);a=A(a,b,0,b.length);b.length=a;return b},db=[];function eb(a,b){db[a]={input:[],output:[],Ec:b};fb(a,gb)}
var gb={open(a){var b=db[a.node.rdev];if(!b)throw new B(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ec.fsync(a.tty)},fsync(a){a.tty.Ec.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ec.Nd)throw new B(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ec.Nd(a.tty)}catch(h){throw new B(29);}if(void 0===g&&0===e)throw new B(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ec.wd)throw new B(60);try{for(var e=0;e<d;e++)a.tty.Ec.wd(a.tty,b[c+e])}catch(f){throw new B(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},hb={Nd(){a:{if(!ab.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ab=cb(a)}a=ab.shift()}return a},wd(a,b){null===b||10===b?(ma(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(ma(z(a.output)),a.output=[])},re(){return{He:25856,Je:5,Ge:191,Ie:35387,Fe:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},se(){return 0},te(){return[24,80]}},ib={wd(a,b){null===b||10===b?(m(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(m(z(a.output)),a.output=[])}},C={Bc:null,Dc(){return C.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new B(63);C.Bc||(C.Bc={dir:{node:{Gc:C.uc.Gc,Cc:C.uc.Cc,
lookup:C.uc.lookup,gd:C.uc.gd,rename:C.uc.rename,unlink:C.uc.unlink,rmdir:C.uc.rmdir,readdir:C.uc.readdir,symlink:C.uc.symlink},stream:{Ac:C.tc.Ac}},file:{node:{Gc:C.uc.Gc,Cc:C.uc.Cc},stream:{Ac:C.tc.Ac,read:C.tc.read,write:C.tc.write,vd:C.tc.vd,Rd:C.tc.Rd}},link:{node:{Gc:C.uc.Gc,Cc:C.uc.Cc,readlink:C.uc.readlink},stream:{}},Gd:{node:{Gc:C.uc.Gc,Cc:C.uc.Cc},stream:jb}});c=kb(a,b,c,d);D(c.mode)?(c.uc=C.Bc.dir.node,c.tc=C.Bc.dir.stream,c.sc={}):32768===(c.mode&61440)?(c.uc=C.Bc.file.node,c.tc=C.Bc.file.stream,
c.vc=0,c.sc=null):40960===(c.mode&61440)?(c.uc=C.Bc.link.node,c.tc=C.Bc.link.stream):8192===(c.mode&61440)&&(c.uc=C.Bc.Gd.node,c.tc=C.Bc.Gd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.sc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Ze(a){return a.sc?a.sc.subarray?a.sc.subarray(0,a.vc):new Uint8Array(a.sc):new Uint8Array(0)},uc:{Gc(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;D(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=
a.vc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Cc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.vc!=b&&(0==b?(a.sc=null,a.vc=0):(c=a.sc,a.sc=new Uint8Array(b),c&&a.sc.set(c.subarray(0,Math.min(b,a.vc))),a.vc=b)))},lookup(){C.md||(C.md=new B(44),C.md.stack="<generic error, no stack>");throw C.md;
},gd(a,b,c,d){return C.createNode(a,b,c,d)},rename(a,b,c){try{var d=lb(b,c)}catch(f){}if(d){if(D(a.mode))for(var e in d.sc)throw new B(55);mb(d)}delete a.parent.sc[a.name];b.sc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.sc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=lb(a,b),d;for(d in c.sc)throw new B(55);delete a.sc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.sc)]},symlink(a,b,c){a=C.createNode(a,b,41471,0);a.link=
c;return a},readlink(a){if(40960!==(a.mode&61440))throw new B(28);return a.link}},tc:{read(a,b,c,d,e){var f=a.node.sc;if(e>=a.node.vc)return 0;a=Math.min(a.node.vc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.sc||a.sc.subarray)){if(f)return a.sc=b.subarray(c,c+d),a.vc=d;if(0===a.vc&&0===e)return a.sc=b.slice(c,c+d),a.vc=d;if(e+d<=a.vc)return a.sc.set(b.subarray(c,
c+d),e),d}f=e+d;var g=a.sc?a.sc.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.sc,a.sc=new Uint8Array(f),0<a.vc&&a.sc.set(g.subarray(0,a.vc),0));if(a.sc.subarray&&b.subarray)a.sc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.sc[e+f]=b[c+f];a.vc=Math.max(a.vc,e+d);return d},Ac(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.vc);if(0>b)throw new B(28);return b},vd(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new B(43);a=a.node.sc;
if(e&2||!a||a.buffer!==p.buffer){d=!0;y();e=void 0;if(!e)throw new B(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{wc:e,Ce:d}},Rd(a,b,c,d){C.tc.write(a,b,0,d,c,!1);return 0}}},nb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ob=async a=>{a=await ja(a);return new Uint8Array(a)},pb=[],sb=async(a,b)=>{"undefined"!=typeof qb&&rb();for(var c of pb)if(c.canHandle(b))return c.handle(a,b);return a},tb=null,
ub={},vb=[],wb=1,xb=null,yb=!1,zb=!0,Ab={},B=class{name="ErrnoError";constructor(a){this.zc=a}},Bb=class{yc={};node=null;get flags(){return this.yc.flags}set flags(a){this.yc.flags=a}get position(){return this.yc.position}set position(a){this.yc.position=a}},Cb=class{uc={};tc={};Rc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Dc=a.Dc;this.id=wb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=
365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ve(){return D(this.mode)}get ue(){return 8192===(this.mode&61440)}};
function Db(a,b={}){if(!a)throw new B(44);b.qd??(b.qd=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=tb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Wa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Va(e+"/"+a[f]);try{d=lb(d,a[f])}catch(h){if(44===h?.zc&&g&&b.xe)return{path:e};throw h;}!d.Rc||g&&!b.qd||(d=d.Rc.root);if(40960===(d.mode&61440)&&(!g||b.pd)){if(!d.uc.readlink)throw new B(52);
d=d.uc.readlink(d);"/"===d.charAt(0)||(d=Wa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new B(32);}function Eb(a){for(var b;;){if(a===a.parent)return a=a.Dc.Qd,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%xb.length}
function mb(a){var b=Fb(a.parent.id,a.name);if(xb[b]===a)xb[b]=a.Jc;else for(b=xb[b];b;){if(b.Jc===a){b.Jc=a.Jc;break}b=b.Jc}}function lb(a,b){var c=D(a.mode)?(c=Gb(a,"x"))?c:a.uc.lookup?0:2:54;if(c)throw new B(c);for(c=xb[Fb(a.id,b)];c;c=c.Jc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.uc.lookup(a,b)}function kb(a,b,c,d){a=new Cb(a,b,c,d);b=Fb(a.parent.id,a.name);a.Jc=xb[b];return xb[b]=a}function D(a){return 16384===(a&61440)}
function Hb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(zb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ib(a,b){if(!D(a.mode))return 54;try{return lb(a,b),20}catch(c){}return Gb(a,"wx")}function Jb(a){a=vb[a];if(!a)throw new B(8);return a}
function Kb(a,b=-1){a=Object.assign(new Bb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!vb[b])break a;throw new B(33);}a.fd=b;return vb[b]=a}function Lb(a,b=-1){a=Kb(a,b);a.tc?.Re?.(a);return a}function Mb(a,b){var c=null?.tc.Cc,d=c?null:a;c??=a.uc.Cc;if(!c)throw new B(63);c(d,b)}var jb={open(a){a.tc=ub[a.node.rdev].tc;a.tc.open?.(a)},Ac(){throw new B(70);}};function fb(a,b){ub[a]={tc:b}}
function Nb(a,b){var c="/"===b;if(c&&tb)throw new B(10);if(!c&&b){var d=Db(b,{qd:!1});b=d.path;d=d.node;if(d.Rc)throw new B(10);if(!D(d.mode))throw new B(54);}b={type:a,ef:{},Qd:b,we:[]};a=a.Dc(b);a.Dc=b;b.root=a;c?tb=a:d&&(d.Rc=b,d.Dc&&d.Dc.we.push(b))}function Ob(a,b,c){var d=Db(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new B(28);if("."===a||".."===a)throw new B(20);var e=Ib(d,a);if(e)throw new B(e);if(!d.uc.gd)throw new B(63);return d.uc.gd(d,a,b,c)}
function Pb(a,b=438){return Ob(a,b&4095|32768,0)}function E(a){return Ob(a,16895,0)}function Qb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ob(a,b|8192,c)}function Rb(a,b){if(!Za(a))throw new B(44);var c=Db(b,{parent:!0}).node;if(!c)throw new B(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Ib(c,b);if(d)throw new B(d);if(!c.uc.symlink)throw new B(63);c.uc.symlink(c,b,a)}
function Sb(a){var b=Db(a,{parent:!0}).node;if(!b)throw new B(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=lb(b,a);a:{try{var d=lb(b,a)}catch(f){d=f.zc;break a}var e=Gb(b,"wx");d=e?e:D(d.mode)?31:0}if(d)throw new B(d);if(!b.uc.unlink)throw new B(63);if(c.Rc)throw new B(10);b.uc.unlink(b,a);mb(c)}function Tb(a,b){a="string"==typeof a?Db(a,{pd:!0}).node:a;Mb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Qe:void 0})}
function Ub(a,b,c=438){if(""===a)throw new B(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=Db(a,{pd:!(b&131072),xe:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new B(20);}else{if(e)throw new B(31);d=Ob(a,c|511,0);f=!0}if(!d)throw new B(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!D(d.mode))throw new B(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:D(d.mode)&&("r"!==Hb(b)||b&576)?31:Gb(d,Hb(b)):44))throw new B(e);if(b&512&&!f){e=d;e="string"==typeof e?Db(e,{pd:!0}).node:e;if(D(e.mode))throw new B(31);if(32768!==(e.mode&61440))throw new B(28);var g=Gb(e,"w");if(g)throw new B(g);Mb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Kb({node:d,path:Eb(d),flags:b,seekable:!0,position:0,tc:d.tc,ze:[],error:!1});e.tc.open&&e.tc.open(e);f&&Tb(d,c&511);!k.logReadFiles||b&1||a in Ab||(Ab[a]=1);return e}
function Vb(a){if(null===a.fd)throw new B(8);a.rd&&(a.rd=null);try{a.tc.close&&a.tc.close(a)}catch(b){throw b;}finally{vb[a.fd]=null}a.fd=null}function Wb(a,b,c){if(null===a.fd)throw new B(8);if(!a.seekable||!a.tc.Ac)throw new B(70);if(0!=c&&1!=c&&2!=c)throw new B(28);a.position=a.tc.Ac(a,b,c);a.ze=[]}
function Xb(a,b,c,d,e,f){if(0>d||0>e)throw new B(28);if(null===a.fd)throw new B(8);if(0===(a.flags&2097155))throw new B(8);if(D(a.node.mode))throw new B(31);if(!a.tc.write)throw new B(28);a.seekable&&a.flags&1024&&Wb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new B(70);b=a.tc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Yb(a,b){a="string"==typeof a?a:Eb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Va(a+"/"+c);try{E(d)}catch(e){if(20!=e.zc)throw e;}a=d}}return d}function Zb(a,b,c,d){a=Va(("string"==typeof a?a:Eb(a))+"/"+b);return Pb(a,nb(c,d))}
function $b(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Eb(a),g=b?Va(a+"/"+b):a);a=nb(d,e);g=Pb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Tb(g,a|146);b=Ub(g,577);Xb(b,c,0,c.length,0,f);Vb(b);Tb(g,a)}}
function ac(a,b,c,d){a=Va(("string"==typeof a?a:Eb(a))+"/"+b);b=nb(!!c,!!d);ac.Od??(ac.Od=64);var e=ac.Od++<<8|0;fb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,n){for(var l=0,t=0;t<n;t++){try{var u=c()}catch(x){throw new B(29);}if(void 0===u&&0===l)throw new B(6);if(null===u||void 0===u)break;l++;g[h+t]=u}l&&(f.node.atime=Date.now());return l},write(f,g,h,n){for(var l=0;l<n;l++)try{d(g[h+l])}catch(t){throw new B(29);}n&&(f.node.mtime=f.node.ctime=Date.now());return l}});
return Qb(a,b,e)}function bc(a){if(!(a.ue||a.ve||a.link||a.sc))if(globalThis.XMLHttpRequest)y("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.sc=ka(a.url)}catch(b){throw new B(29);}}
function cc(a,b,c,d,e){class f{Bd=!1;yc=[];Ad=void 0;ce=0;ae=0;get(l){if(!(l>this.length-1||0>l)){var t=l%this.chunkSize;return this.Ad(l/this.chunkSize|0)[t]}}Ae(l){this.Ad=l}he(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||y("Couldn't load "+c+". Status: "+l.status);var t=Number(l.getResponseHeader("Content-length")),u,x=(u=l.getResponseHeader("Accept-Ranges"))&&"bytes"===u;l=(u=l.getResponseHeader("Content-Encoding"))&&"gzip"===u;var F=
1048576;x||(F=t);var I=this;I.Ae(W=>{var T=W*F,Q=(W+1)*F-1;Q=Math.min(Q,t-1);if("undefined"==typeof I.yc[W]){var Ma=I.yc;T>Q&&y("invalid range ("+T+", "+Q+") or no bytes requested!");Q>t-1&&y("only "+t+" bytes available! programmer error!");var R=new XMLHttpRequest;R.open("GET",c,!1);t!==F&&R.setRequestHeader("Range","bytes="+T+"-"+Q);R.responseType="arraybuffer";R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");R.send(null);200<=R.status&&300>R.status||304===R.status||
y("Couldn't load "+c+". Status: "+R.status);T=void 0!==R.response?new Uint8Array(R.response||[]):cb(R.responseText||"");Ma[W]=T}"undefined"==typeof I.yc[W]&&y("doXHR failed!");return I.yc[W]});if(l||!t)F=t=1,F=t=this.Ad(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.ce=t;this.ae=F;this.Bd=!0}get length(){this.Bd||this.he();return this.ce}get chunkSize(){this.Bd||this.he();return this.ae}}if(globalThis.XMLHttpRequest){ba||y("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var h=void 0}else h=c,g=void 0;var n=Zb(a,b,d,e);g?n.sc=g:h&&(n.sc=null,n.url=h);Object.defineProperties(n,{vc:{get:function(){return this.sc.length}}});a={};for(const [l,t]of Object.entries(n.tc))a[l]=(...u)=>{bc(n);return t(...u)};a.read=(l,t,u,x,F)=>{bc(n);l=l.node.sc;if(F>=l.length)t=0;else{x=Math.min(l.length-F,x);if(l.slice)for(var I=0;I<x;I++)t[u+I]=l[F+I];else for(I=0;I<x;I++)t[u+I]=l.get(F+I);t=x}return t};a.vd=()=>{bc(n);y();throw new B(48);};n.tc=a;return n}
var dc={},Sa=void 0,ec=a=>0===a%4&&(0!==a%100||0===a%400),fc=[0,31,60,91,121,152,182,213,244,274,305,335],gc=[0,31,59,90,120,151,181,212,243,273,304,334],qc=(a,b)=>{hc=a;ic=b;if(jc)if(kc||=!0,0==a)lc=function(){setTimeout(mc,Math.max(0,nc+b-performance.now())|0)};else if(1==a)lc=function(){oc(mc)};else if(2==a){if(!pc)if(globalThis.setImmediate)pc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);
pc=d=>{c.push(d);if(ba){let e;(e=k).setImmediates??(e.setImmediates=[]);k.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}lc=function(){pc(mc)}}},rc=a=>{pa=a;Ja||(k.onExit?.(a),oa=!0);fa(a,new Aa(a))},sc=a=>{a instanceof Aa||"unwind"==a||fa(1,a)},tc=()=>{if(!Ja)try{var a=pa;pa=a;rc(a)}catch(b){sc(b)}},Cc=(a,b,c,d,e)=>{function f(){return g<uc?(tc(),!1):!0}jc=a;vc=d;var g=uc;kc=!1;mc=function(){if(!oa)if(0<wc.length){var h=wc.shift();h.Xe(h.De);if(xc){var n=
xc,l=0==n%1?n-1:Math.floor(n);xc=h.Le?l:(8*n+(l+.5))/9}k.setStatus&&(h=k.statusMessage||"Please wait...",n=xc??0,l=yc.Se??0,n?n<l?k.setStatus("{message} ({expected - remaining}/{expected})"):k.setStatus(h):k.setStatus(""));f()&&setTimeout(mc,0)}else if(f())if(zc=zc+1|0,1==hc&&1<ic&&0!=zc%ic)lc();else{0==hc&&(nc=performance.now());a:if(!oa){for(h of Ac)if(!1===h())break a;if(!oa)try{a(),tc()}catch(t){sc(t)}for(n of Bc)n()}f()&&lc()}};e||(0<b?qc(0,1E3/b):qc(1,1),lc());if(c)throw"unwind";},kc=!1,lc=
null,uc=0,jc=null,vc=0,hc=0,ic=0,zc=0,wc=[],Ac=[],Bc=[];function Dc(){lc=null;uc++}var Ec=0;function oc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ec)Ec=b+1E3/60;else for(;b+2>=Ec;)Ec+=1E3/60;setTimeout(a,Math.max(Ec-b,0))}}var yc={},nc,mc,pc,xc,Fc=[],G=a=>{var b=Fc[a];b||(Fc[a]=b=Gc.get(a));return b};function Hc(a){var b=H.xc[a];b.target.removeEventListener(b.Qc,b.Jd,b.Yd);H.xc.splice(a,1)}
function Ic(){if(navigator.userActivation?navigator.userActivation.isActive:H.td&&H.le.ie){var a=H.Fc;H.Fc=[];for(var b of a)b.zd(...b.Fd)}}function Jc(a){if(!a.target)return-4;if(a.ld)a.Jd=function(c){++H.td;H.le=a;Ic();a.oe(c);Ic();--H.td},a.target.addEventListener(a.Qc,a.Jd,a.Yd),H.xc.push(a);else for(var b=0;b<H.xc.length;++b)H.xc[b].target==a.target&&H.xc[b].Qc==a.Qc&&Hc(b--);return 0}
var H={Ee:0,Ye:0,af:0,cf:0,Dd:0,pf:0,Ve:0,Oe:0,ff:0,Ne:0,We:0,gf:0,qf:0,nf:0,hf(){for(;H.xc.length;)Hc(H.xc.length-1);H.Fc=[]},td:0,Fc:[],Me(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var h in f)if(f[h]!=g[h])return!1;return!0}for(var e of H.Fc)if(e.zd==a&&d(e.Fd,c))return;H.Fc.push({zd:a,Td:b,Fd:c});H.Fc.sort((f,g)=>f.Td<g.Td)},kf(a){H.Fc=H.Fc.filter(b=>b.zd!=a)},xc:[],jf:(a,b)=>{for(var c=0;c<H.xc.length;++c)H.xc[c].target!=a||b&&b!=H.xc[c].Qc||Hc(c--)},lf(a){let b=!1;for(let c=0;c<
H.xc.length;++c){const d=H.xc[c];d.target===a.target&&d.Kd===a.Kd&&d.ld===a.ld&&d.Zd===a.Zd&&(Hc(c--),b=!0)}return b?0:-5},$e(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Kc=[0,globalThis.document??0,globalThis.window??0],Mc=(a,b,c,d)=>{H.Dd||(H.Dd=Lc(96));return Jc({target:a,ie:!0,Qc:"wheel",Kd:9,Zd:b,ld:d,oe:e=>{var f=H.Dd;sa[f>>3]=e.timeStamp;var g=f>>2;r[g+2]=e.screenX;r[g+3]=e.screenY;
r[g+4]=e.clientX;r[g+5]=e.clientY;p[f+24]=e.ctrlKey;p[f+25]=e.shiftKey;p[f+26]=e.altKey;p[f+27]=e.metaKey;qa[2*g+14]=e.button;qa[2*g+15]=e.buttons;r[g+8]=e.movementX;r[g+9]=e.movementY;var h=0>Kc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};r[g+10]=e.clientX-(h.left|0);r[g+11]=e.clientY-(h.top|0);sa[f+64>>3]=e.deltaX;sa[f+72>>3]=e.deltaY;sa[f+80>>3]=e.deltaZ;r[f+88>>2]=e.deltaMode;G(d)(9,f,b)&&e.preventDefault()},Yd:c})},Nc={},Pc=()=>{if(!Oc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",
PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Nc)void 0===Nc[b]?delete a[b]:a[b]=Nc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Oc=c}return Oc},Oc,J,Qc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,
g))},Rc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Sc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Tc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Uc=1,Vc=[],K=[],Wc=[],L=[],Xc=[],Yc=[],Zc=[],$c=[1,1,2,2,4,4,4,2,3,4,8],ad={},bd=4,cd=0,dd=a=>{for(var b=Uc++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=Uc++;return b},ed=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=J[c](),g=f&&dd(d);f?(f.name=g,d[g]=f):M||=1282;r[b+4*e>>2]=g}},fd=a=>{a=32-Math.clz32(0===a?0:a-1);var b=N.Kc[a];if(b)return b;b=J.getParameter(34965);N.Kc[a]=J.createBuffer();J.bindBuffer(34963,N.Kc[a]);J.bufferData(34963,1<<a,
35048);J.bindBuffer(34963,b);return N.Kc[a]},hd=a=>{gd=!1;for(var b=0;b<N.ud;++b){var c=N.Mc[b];if(c.Wc&&c.enabled){gd=!0;var d=c.size;var e=c.type,f=c.stride;d=0<f?a*f:d*$c[e-5120]*a;e=32-Math.clz32(0===d?0:d-1);f=N.Lc[e];var g=N.Hc[e];N.Hc[e]=N.Hc[e]+1&63;var h=f[g];h?e=h:(h=J.getParameter(34964),f[g]=J.createBuffer(),J.bindBuffer(34962,f[g]),J.bufferData(34962,1<<e,35048),J.bindBuffer(34962,h),e=f[g]);J.bindBuffer(34962,e);J.bufferSubData(34962,0,q.subarray(c.wc,c.wc+d));c.be.call(J,b,c.size,c.type,
c.Sd,c.stride,0)}}},kd=(a,b)=>{a.yc||(a.yc=a.getContext,a.getContext=function(d,e){e=a.yc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Pd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?jd(c,b):0},jd=(a,b)=>{var c=dd(Yc),d={handle:c,attributes:b,version:b.Pd,Uc:a};a.canvas&&(a.canvas.Be=d);Yc[c]=d;if("undefined"==typeof b.ne||b.ne)if((a=d)||(a=N),!a.pe){a.pe=!0;b=a.Uc;b.df=b.getExtension("WEBGL_multi_draw");b.Ue=b.getExtension("EXT_polygon_offset_clamp");
b.Te=b.getExtension("EXT_clip_control");b.rf=b.getExtension("WEBGL_polygon_mode");Qc(b);Rc(b);Sc(b);b.Pe=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.bf=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Id=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Id)b.Id=b.getExtension("EXT_disjoint_timer_query");for(var e of Tc(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}d.ud=d.Uc.getParameter(34921);
d.Mc=[];for(e=0;e<d.ud;e++)d.Mc[e]={enabled:!1,Wc:!1,size:0,type:0,Sd:0,stride:0,wc:0,be:null};d.Hc=[];d.kd=[];d.Hc.length=d.kd.length=22;d.Lc=[];d.Sc=[];d.Lc.length=d.Sc.length=22;d.Kc=[];d.Kc.length=22;for(e=0;21>=e;++e){d.Kc[e]=null;d.Hc[e]=d.kd[e]=0;d.Lc[e]=[];d.Sc[e]=[];a=d.Lc[e];b=d.Sc[e];a.length=b.length=64;for(var f=0;64>f;++f)a[f]=b[f]=null}return c},ld={},M,N,gd,md=()=>{var a=Tc(J);return a=a.concat(a.map(b=>"GL_"+b))},nd=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;
case 34814:case 36345:c=0;break;case 34466:var d=J.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>N.version){M||=1282;return}c=md().length;break;case 33307:case 33308:if(2>N.version){M||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=J.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":M||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:M||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)r[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){M||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:M||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}r[b>>2]=c}else M||=1281},od=
a=>{var b=bb(a)+1,c=Lc(b);c&&A(a,q,c,b);return c},pd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),qd=a=>{a-=5120;return 0==a?p:1==a?q:2==a?qa:4==a?r:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?v:ra},rd=(a,b,c,d,e)=>{a=qd(a);b=d*((cd||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+bd-1&-bd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},sd=a=>{var b=J.me;if(b){var c=b.Tc[a];"number"==typeof c&&
(b.Tc[a]=c=J.getUniformLocation(b,b.Wd[a]+(0<c?`[${c}]`:"")));return c}M||=1282},td=[];function ud(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var vd=a=>{setTimeout(()=>{if(!oa)try{a(),tc()}catch(b){sc(b)}},1E4)},wd=!1,xd=!1,yd=[];
function rb(){function a(){xd=document.pointerLockElement===k.canvas}if(!zd){zd=!0;pb.push({canHandle:function(c){return!k.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:async function(c,d){var e=new Blob([c],{type:Ad(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Ad(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var n=new Image;n.onload=()=>{var l=document.createElement("canvas");l.width=n.width;l.height=n.height;l.getContext("2d").drawImage(n,
0,0);URL.revokeObjectURL(f);g(c)};n.onerror=()=>{m(`Image ${f} could not be decoded`);h()};n.src=f})}});pb.push({canHandle:function(c){return!k.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:async function(c,d){return new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=new Blob([c],{type:Ad(d)});h=URL.createObjectURL(h);var n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){m(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var l="data:audio/x-"+d.slice(-3)+";base64,",t="",u=0,x=0,F=0;F<c.length;F++)for(u=u<<8|c[F],x+=8;6<=x;){var I=u>>x-6&63;x-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[I]}2==x?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==x&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");n.src=l+t;f(n)}};n.src=h;vd(()=>{f(n)})})}});var b=k.canvas;b&&(document.addEventListener("pointerlockchange",
a,!1),k.elementPointerLock&&b.addEventListener("click",c=>{!xd&&k.canvas.requestPointerLock&&(k.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Bd(a){var b={antialias:1<Cd[135181],depth:0<Cd[135173],stencil:0<Cd[135174],alpha:0<Cd[135172]};if(!k.ctx||a!=k.canvas){var c,d={antialias:!1,alpha:!1,Pd:"undefined"!=typeof WebGL2RenderingContext?2:1};if(b)for(var e in b)d[e]=b[e];if("undefined"!=typeof ld&&(c=kd(a,d)))var f=Yc[c].Uc;f&&(k.ctx=f,N=Yc[c],k.ctx=J=N?.Uc,yd.forEach(g=>g()),rb())}}var Dd=!1,Ed=void 0,O=void 0;
function Fd(a,b){function c(){wd=!1;var f=d.parentNode;ud()===f?(d.exitFullscreen=Gd,Ed&&d.requestPointerLock(),wd=!0,O?Hd():P(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),O?Id():P(d));k.onFullScreen?.(wd);k.onFullscreen?.(wd)}Ed=a;O=b;"undefined"==typeof Ed&&(Ed=!0);"undefined"==typeof O&&(O=!1);var d=k.canvas;Dd||(Dd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,
!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Gd(){if(!wd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}function Ad(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var Jd=0,Kd=0,Ld=0,Md=0;
function Nd(a,b){var c=k.canvas,d=c.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+d.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+d.top;a*=c.width/d.width;b*=c.height/d.height;return{x:a,y:b}}function Od(a,b){const {x:c,y:d}=Nd(a,b);Ld=c-Jd;Md=d-Kd;Jd=c;Kd=d}
function Pd(a){xd?("mousemove"!=a.type&&"mozMovementX"in a?Ld=Md=0:(Ld=a.movementX||a.mozMovementX||a.webkitMovementX||0,Md=a.movementY||a.mozMovementY||a.webkitMovementY||0),Jd+=Ld,Kd+=Md):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.mf,void 0!==a&&Nd(a.pageX,a.pageY)):Od(a.pageX,a.pageY)}var Qd=[];function Rd(){var a=k.canvas;Qd.forEach(b=>b(a.width,a.height))}function Hd(){"undefined"!=typeof SDL&&(r[SDL.screen>>2]=v[SDL.screen>>2]|8388608);P(k.canvas);Rd()}
function Id(){"undefined"!=typeof SDL&&(r[SDL.screen>>2]=v[SDL.screen>>2]&-8388609);P(k.canvas);Rd()}
function P(a,b,c){b&&c?(a.Ed=b,a.sd=c):(b=a.Ed,c=a.sd);var d=b,e=c;0<k.forcedAspectRatio&&(d/e<k.forcedAspectRatio?d=Math.round(e*k.forcedAspectRatio):e=Math.round(d/k.forcedAspectRatio));if(ud()===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}O?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=
c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qb={},zd;
function Sd(a,b,c,d,e,f){this.id=a;this.y=this.x=0;this.$c=!1;this.Vd=this.Ud=0;this.width=b;this.height=c;this.Zc=d;this.Yc=e;this.yd=b;this.xd=c;this.title=f;this.attributes={...Cd};this.ad={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.nd=[];this.ye=0;this.title=null;this.$d=this.Vc=this.bd=this.od=this.jd=this.Ic=this.Pc=this.hd=this.ee=this.Md=this.fe=this.de=this.ge=0}
var U=a=>0>=a||!S?null:S[a-1],Td=0,Ud=0,V=null,Vd=null,S=null,Wd=null,Xd=null,Yd=null,Cd=null,Zd=null,$d={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},ae=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;
case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;
case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;
case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;
case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;
case 93:return 348;default:return-1}},be=()=>{var a=V,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},ce=a=>{V&&V.Vc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||G(V.Vc)(V.id,a))},de=(a,b)=>{if(V){var c=ae(a);if(-1!=c){var d=b&&V.keys[c];V.keys[c]=b;V.nd[a]=b;V.bd&&(d&&(b=2),G(V.bd)(V.id,c,a,b,be()))}}},fe=()=>{ee()},ge=()=>{ee()},he=a=>{de(a.keyCode,1);"Backspace"!=a.key&&"Tab"!=a.key||a.preventDefault()},ie=a=>{de(a.keyCode,
0)},je=()=>{if(V)for(var a=0;a<V.nd.length;++a)V.nd[a]&&de(a,0)},ke=a=>{if(V){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(Zd===c.identifier){Od(c.pageX,c.pageY);b=!0;break}if(!b)return}else Pd(a);a.target==k.canvas&&V.Pc&&V.Pc&&G(V.Pc)(V.id,Jd,Kd)}},le=a=>{V&&a.target==k.canvas&&V.Ic&&G(V.Ic)(V.id,1)},me=a=>{V&&a.target==k.canvas&&V.Ic&&G(V.Ic)(V.id,0)},ne=(a,b)=>{if(V&&a.target==k.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===
a.type){a.preventDefault();var d=!1;if(null===Zd&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],Zd=d.identifier,Od(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(Zd===e.identifier){Zd=null;d=!0;break}if(!d)return}else Pd(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){V.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else V.buttons&=~(1<<c);V.hd&&G(V.hd)(V.id,c,b,be())}},oe=a=>{V&&ne(a,1)},pe=a=>{V&&ne(a,0)},qe=a=>{var b=
0;switch(a.type){case "DOMMouseScroll":b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:y("unrecognized mouse wheel delta mode: "+a.deltaMode)}break;default:y("unrecognized mouse wheel event: "+a.type)}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(V&&V.jd&&a.target==k.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;G(V.jd)(V.id,b,c);a.preventDefault()}},re=(a,
b,c,d)=>{if(V){var e=!1;ud()?V.$c||(e=a!=screen.width||b!=screen.height,V.Ud=V.x,V.Vd=V.y,V.yd=V.width,V.xd=V.height,V.x=V.y=0,V.width=screen.width,V.height=screen.height,V.$c=!0):1==V.$c&&(e=a!=V.yd||b!=V.xd,V.x=V.Ud,V.y=V.Vd,V.width=V.yd,V.height=V.xd,V.$c=!1);if(e)P(k.canvas,V.width,V.height),Rd();else if(V.width!=a||V.height!=b||V.Zc!=c||V.Yc!=d)V.width=a,V.height=b,V.Zc=c,V.Yc=d,V&&V.ge&&G(V.ge)(V.id,V.width,V.height),V&&V.Md&&G(V.Md)(V.id,V.Zc,V.Yc)}},se={},te=[],ue=null,ee=()=>{if(zc!==ue||
!zc){te=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];ue=zc;for(var a=0;a<te.length;++a){var b=te[a];if(b){se[a]||(ma("glfw joystick connected:",a),se[a]={id:od(b.id),ke:b.buttons.length,je:b.axes.length,buttons:Lc(b.buttons.length),axes:Lc(4*b.axes.length)});for(var c=se[a],d=0;d<b.buttons.length;++d)p[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)w[c.axes+4*d>>2]=b.axes[d]}else se[a]&&(ma("glfw joystick disconnected",a),ve(se[a].id),ve(se[a].buttons),
ve(se[a].axes),delete se[a])}}},we=a=>{function b(h){var n="/.glfw_dropped_files/"+h.name.replace(/\//g,"_"),l=new FileReader;l.onloadend=u=>{if(2!=l.readyState)++f,ma("failed to read dropped file: "+h.name+": "+l.error);else{u=new Uint8Array(u.target.result);var x={};x.flags=x.flags||577;var F=Ub(n,x.flags,x.mode);"string"==typeof u&&(u=new Uint8Array(cb(u)));ArrayBuffer.isView(u)?Xb(F,u,0,u.byteLength,void 0,x.Ke):y("Unsupported data type");Vb(F);if(++f===e){G(V.od)(V.id,e,c);for(u=0;u<d.length;++u)ve(d[u]);
ve(c)}}};l.readAsArrayBuffer(h);var t=od(n);d.push(t);v[c+4*g>>2]=t}if(V&&V.od&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Lc(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;Yb("/",".glfw_dropped_files");for(var g=0;g<e;++g)b(a.dataTransfer.files[g]);return!1}},xe=a=>{if(V&&V.od)return a.preventDefault(),!1},ye=a=>{var b=k.canvas;!xd&&b.requestPointerLock&&(b.requestPointerLock(),a.preventDefault())};
function ze(a,b){function c(){wd=!1;var f=d.parentNode;ud()===f?(d.exitFullscreen=Gd,Ed&&d.requestPointerLock(),wd=!0,O?Hd():(P(d),Rd())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),O?Id():(P(d),Rd()));k.onFullScreen?.(wd);k.onFullscreen?.(wd)}Ed=a;O=b;"undefined"==typeof Ed&&(Ed=!0);"undefined"==typeof O&&(O=!1);var d=k.canvas;Dd||(Dd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",
c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Ae(a,b,c){var d=Be()?Vd:1;b&&c?(a.Ed=b,a.sd=c):(b=a.Ed,c=a.sd);var e=b,f=c;k.forcedAspectRatio&&0<k.forcedAspectRatio&&(e/f<k.forcedAspectRatio?e=Math.round(f*k.forcedAspectRatio):f=Math.round(e/k.forcedAspectRatio));if(ud()===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/f);e=Math.round(e*g);f=Math.round(f*g)}O&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(Be()?(a.style.setProperty("width",
b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}function Ce(a,b){const c=k.canvas.getBoundingClientRect();a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;!Be()&&V&&(a*=V.width/c.width,b*=V.height/c.height);return{x:a,y:b}}function De(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}
function Be(){return V?0<V.attributes[139276]:!1}function Ee(){V&&(P(k.canvas,V.width,V.height),Rd())}function Fe(){Vd=De();V&&V.ee&&G(V.ee)(V.id,Vd,Vd);Ee()}
var He=a=>{var b=bb(a)+1,c=Ge(b);A(a,q,c,b);return c},Ie=(a,b,c,d)=>{var e={string:l=>{var t=0;null!==l&&void 0!==l&&0!==l&&(t=He(l));return t},array:l=>{var t=Ge(l.length);p.set(l,t);return t}};a=k["_"+a];var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var n=e[c[h]];n?(0===g&&(g=X()),f[h]=n(d[h])):f[h]=d[h]}c=a(...f);return c=function(l){0!==g&&Y(g);return"string"===b?l?z(q,l):"":"boolean"===b?!!l:l}(c)},Je=Fd;xb=Array(4096);Nb(C,"/");E("/tmp");E("/home");E("/home/web_user");
(function(){E("/dev");fb(259,{read:()=>0,write:(d,e,f,g)=>g,Ac:()=>0});Qb("/dev/null",259);eb(1280,hb);eb(1536,ib);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ya(a),b=a.byteLength);return a[--b]};ac("/dev","random",c);ac("/dev","urandom",c);E("/dev/shm");E("/dev/shm/tmp")})();
(function(){E("/proc");var a=E("/proc/self");E("/proc/self/fd");Nb({Dc(){var b=kb(a,"fd",16895,73);b.tc={Ac:C.tc.Ac};b.uc={lookup(c,d){c=+d;var e=Jb(c);c={parent:null,Dc:{Qd:"fake"},uc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(vb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();k.requestAnimationFrame=oc;k.pauseMainLoop=Dc;k.resumeMainLoop=function(){uc++;var a=hc,b=ic,c=jc;jc=null;Cc(c,0,!1,vc,!0);qc(a,b);lc()};
k.preMainLoop&&Ac.push(k.preMainLoop);k.postMainLoop&&Bc.push(k.postMainLoop);var Ke=()=>{if(N){var a=N.Lc;N.Lc=N.Sc;N.Sc=a;a=N.Hc;N.Hc=N.kd;N.kd=a;for(a=0;21>=a;++a)N.Hc[a]=0}};"undefined"!=typeof yc&&Ac.push(Ke);for(var Le=new Float32Array(288),Me=0;288>=Me;++Me)td[Me]=Le.subarray(0,Me);k.noExitRuntime&&(Ja=k.noExitRuntime);k.preloadPlugins&&(pb=k.preloadPlugins);k.print&&(ma=k.print);k.printErr&&(m=k.printErr);k.wasmBinary&&(na=k.wasmBinary);k.arguments&&(da=k.arguments);k.thisProgram&&(ea=k.thisProgram);
if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();k.addRunDependency=Ia;k.removeRunDependency=Ha;k.ccall=Ie;k.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?k["_"+a]:(...f)=>Ie(a,b,c,f,d)};k.requestFullscreen=Je;k.FS_preloadFile=async(a,b,c,d,e,f,g,h)=>{var n=b?Za(Va(a+"/"+b)):a,l=`cp ${n}`;Ia(l);try{var t=c;"string"==typeof c&&(t=await ob(c));t=await sb(t,n);h?.();f||$b(a,b,t,d,e,g)}finally{Ha(l)}};
k.FS_unlink=(...a)=>Sb(...a);k.FS_createPath=(...a)=>Yb(...a);k.FS_createDevice=(...a)=>ac(...a);k.FS_createDataFile=(...a)=>$b(...a);k.FS_createLazyFile=(...a)=>cc(...a);
var Lc,ve,Ne,Z,Pa,Y,Ge,X,Oe,Pe,Qa,Qe,va,Gc,xf={Ub:function(a){(a=a?a?z(q,a):"":null)&&window.open(a,"_blank")},q:a=>{var b=new Oa(a);0==p[b.wc+12]&&(p[b.wc+12]=1,La--);p[b.wc+13]=0;Ka.push(b);Pe(a);return Qe(a)},s:()=>{Z(0,0);var a=Ka.pop();Oe(a.Ld);Na=0},a:()=>Ra([]),g:a=>Ra([a]),p:(a,b)=>Ra([a,b]),Ga:()=>{var a=Ka.pop();a||y("no exception to throw");var b=a.Ld;0==p[a.wc+13]&&(Ka.push(a),p[a.wc+13]=1,p[a.wc+12]=0,La++);Na=b;throw Na;},w:(a,b,c)=>{var d=new Oa(a);v[d.wc+16>>2]=0;v[d.wc+4>>2]=b;v[d.wc+
8>>2]=c;Na=a;La++;throw Na;},Fa:()=>La,f:a=>{Na||=a;throw Na;},Ja:function(a,b,c){Sa=c;try{var d=Jb(a);switch(b){case 0:var e=Ta();if(0>e)break;for(;vb[e];)e++;return Lb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ta(),d.flags|=e,0;case 12:return e=Ta(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof dc||"ErrnoError"!==f.name)throw f;return-f.zc}},Eb:function(a,b,c){Sa=c;try{var d=Jb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;
if(d.tty.Ec.re){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ta();r[e>>2]=25856;r[e+4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var f=0;32>f;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ec.se)for(e=Ta(),a=[],f=0;32>f;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Ta();return r[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Ta();
if(!d.tc.qe)throw new B(59);return d.tc.qe(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ec.te&&(f=[24,80],e=Ta(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof dc||"ErrnoError"!==g.name)throw g;return-g.zc}},Fb:function(a,b,c,d){Sa=d;try{b=b?z(q,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Jb(a).path;if(0==e.length)throw new B(44);b=f+"/"+e}var g=d?Ta():0;return Ub(b,c,g).fd}catch(h){if("undefined"==
typeof dc||"ErrnoError"!==h.name)throw h;return-h.zc}},rb:()=>y(""),Jb:a=>{do{var b=v[a>>2];a+=4;var c=v[a>>2];a+=4;var d=v[a>>2];a+=4;b=b?z(q,b):"";Yb("/",Wa(b));$b(b,null,p.subarray(d,d+c),!0,!0,!0)}while(v[a>>2])},Ib:(a,b)=>{b=b?z(q,b):"";if(a&24){var c=b=b.replace(/\s+$/,"");b=0<b.length?"\n":"";var d=Error().stack.toString(),e=d.split("\n");d="";var f=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),g=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),h;for(h of e){var n=g.exec(h);if(5==n?.length){e=n[1];
var l=n[2];var t=n[3];n=n[4]}else if(n=f.exec(h),4<=n?.length)e=n[1],l=n[2],t=n[3],n=n[4]|0;else{d+=h+"\n";continue}"_emscripten_log"==e||"_emscripten_get_callstack"==e?d="":a&24&&(a&64&&(l=l.substring(l.replace(/\\/g,"/").lastIndexOf("/")+1)),d+=`    at ${e} (${l}:${t}:${n})\n`)}d=d.replace(/\s+$/,"");b=c+(b+d)}a&1?a&4?console.error(b):a&2?console.warn(b):a&512?console.info(b):a&256?console.debug(b):console.log(b):a&6?m(b):ma(b)},xb:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);
a=new Date(1E3*a);r[b>>2]=a.getUTCSeconds();r[b+4>>2]=a.getUTCMinutes();r[b+8>>2]=a.getUTCHours();r[b+12>>2]=a.getUTCDate();r[b+16>>2]=a.getUTCMonth();r[b+20>>2]=a.getUTCFullYear()-1900;r[b+24>>2]=a.getUTCDay();r[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},yb:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);r[b>>2]=a.getSeconds();r[b+4>>2]=a.getMinutes();r[b+8>>2]=a.getHours();r[b+12>>2]=a.getDate();r[b+16>>2]=a.getMonth();r[b+20>>
2]=a.getFullYear()-1900;r[b+24>>2]=a.getDay();r[b+28>>2]=(ec(a.getFullYear())?fc:gc)[a.getMonth()]+a.getDate()-1|0;r[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();r[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},zb:function(a){var b=new Date(r[a+20>>2]+1900,r[a+16>>2],r[a+12>>2],r[a+8>>2],r[a+4>>2],r[a>>2],0),c=r[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),
f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?r[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));r[a+24>>2]=b.getDay();r[a+28>>2]=(ec(b.getFullYear())?fc:gc)[b.getMonth()]+b.getDate()-1|0;r[a>>2]=b.getSeconds();r[a+4>>2]=b.getMinutes();r[a+8>>2]=b.getHours();r[a+12>>2]=b.getDate();r[a+16>>2]=b.getMonth();r[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},Ab:function(a){var b=new Date(Date.UTC(r[a+20>>
2]+1900,r[a+16>>2],r[a+12>>2],r[a+8>>2],r[a+4>>2],r[a>>2],0));r[a+24>>2]=b.getUTCDay();r[a+28>>2]=(b.getTime()-Date.UTC(b.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;return BigInt(b.getTime()/1E3)},Bb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(f,e);r[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);
e<f?(A(a,q,c,17),A(b,q,d,17)):(A(a,q,d,17),A(b,q,c,17))},wb:function(a,b,c){if(!(0<=a&&3>=a))return 28;ta[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Ba:()=>{Dc();jc=null},vb:a=>{var b=q.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-va.buffer.byteLength+65535)/65536|0;try{va.grow(d);ua();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
qb:(a,b,c)=>{a=G(a);Cc(a,b,c)},Za:(a,b,c,d)=>{a=2<a?a?z(q,a):"":a;return(a=Kc[a]||globalThis.document?.querySelector(a))?"undefined"!=typeof a.onwheel?Mc(a,b,c,d):-1:-4},Gb:(a,b)=>{var c=0,d=0,e;for(e of Pc()){var f=b+c;v[a+d>>2]=f;c+=A(e,q,f,Infinity)+1;d+=4}return 0},Hb:(a,b)=>{var c=Pc();v[a>>2]=c.length;a=0;for(var d of c)a+=bb(d)+1;v[b>>2]=a;return 0},Ha:function(a){try{var b=Jb(a);Vb(b);return 0}catch(c){if("undefined"==typeof dc||"ErrnoError"!==c.name)throw c;return c.zc}},Db:function(a,b,
c,d){try{a:{var e=Jb(a);a=b;for(var f,g=b=0;g<c;g++){var h=v[a>>2],n=v[a+4>>2];a+=8;var l=e,t=h,u=n,x=f,F=p;if(0>u||0>x)throw new B(28);if(null===l.fd)throw new B(8);if(1===(l.flags&2097155))throw new B(8);if(D(l.node.mode))throw new B(31);if(!l.tc.read)throw new B(28);var I="undefined"!=typeof x;if(!I)x=l.position;else if(!l.seekable)throw new B(70);var W=l.tc.read(l,F,t,u,x);I||(l.position+=W);var T=W;if(0>T){var Q=-1;break a}b+=T;if(T<n)break;"undefined"!=typeof f&&(f+=T)}Q=b}v[d>>2]=Q;return 0}catch(Ma){if("undefined"==
typeof dc||"ErrnoError"!==Ma.name)throw Ma;return Ma.zc}},Cb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Jb(a);Wb(e,b,c);ta[d>>3]=BigInt(e.position);e.rd&&0===b&&0===c&&(e.rd=null);return 0}catch(f){if("undefined"==typeof dc||"ErrnoError"!==f.name)throw f;return f.zc}},Ia:function(a,b,c,d){try{a:{var e=Jb(a);a=b;for(var f,g=b=0;g<c;g++){var h=v[a>>2],n=v[a+4>>2];a+=8;var l=Xb(e,p,h,n,f);if(0>l){var t=-1;break a}b+=l;if(l<n)break;"undefined"!=
typeof f&&(f+=l)}t=b}v[d>>2]=t;return 0}catch(u){if("undefined"==typeof dc||"ErrnoError"!==u.name)throw u;return u.zc}},Oa:a=>J.activeTexture(a),N:(a,b)=>{J.attachShader(K[a],L[b])},E:(a,b)=>{if(b&&!Vc[b]){var c=J.createBuffer();c.name=b;Vc[b]=c}34962==a?J.Nc=b:34963==a&&(J.Oc=b);35051==a?J.Hd=b:35052==a&&(J.Xc=b);J.bindBuffer(a,Vc[b])},La:(a,b)=>{J.bindSampler(a,Zc[b])},F:(a,b)=>{J.bindTexture(a,Wc[b])},t:a=>{J.bindVertexArray(Xc[a]);a=J.getParameter(34965);J.Oc=a?a.name|0:0},Kb:a=>J.blendEquation(a),
Pb:(a,b)=>J.blendEquationSeparate(a,b),Ka:(a,b,c,d)=>J.blendFuncSeparate(a,b,c,d),J:(a,b,c,d)=>{2<=N.version?c&&b?J.bufferData(a,q,d,c,b):J.bufferData(a,b,d):J.bufferData(a,c?q.subarray(c,c+b):b,d)},Na:(a,b,c,d)=>{2<=N.version?c&&J.bufferSubData(a,b,q,d,c):J.bufferSubData(a,b,q.subarray(d,d+c))},za:a=>J.clear(a),fa:(a,b,c,d)=>J.clearColor(a,b,c,d),Z:a=>{J.compileShader(L[a])},va:()=>{var a=dd(K),b=J.createProgram();b.name=a;b.ed=b.cd=b.dd=0;b.Cd=1;K[a]=b;return a},$:a=>{var b=dd(L);L[b]=J.createShader(a);
return b},ca:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Vc[d];e&&(J.deleteBuffer(e),e.name=0,Vc[d]=null,d==J.Nc&&(J.Nc=0),d==J.Oc&&(J.Oc=0),d==J.Hd&&(J.Hd=0),d==J.Xc&&(J.Xc=0))}},ta:a=>{if(a){var b=K[a];b?(J.deleteProgram(b),b.name=0,K[a]=null):M||=1281}},aa:a=>{if(a){var b=L[a];b?(J.deleteShader(b),L[a]=null):M||=1281}},Qa:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Wc[d];e&&(J.deleteTexture(e),e.name=0,Wc[d]=null)}},xa:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];J.deleteVertexArray(Xc[d]);
Xc[d]=null}},Pa:(a,b)=>{J.detachShader(K[a],L[b])},C:a=>J.disable(a),P:(a,b,c)=>{hd(b+c);J.drawArrays(a,b,c);gd&&J.bindBuffer(34962,Vc[J.Nc])},Rb:(a,b,c,d)=>{var e=0;if(!J.Oc){var f=1*$c[c-5120]*b;var g=fd(f);J.bindBuffer(34963,g);J.bufferSubData(34963,0,q.subarray(d,d+f));if(0<b)for(g=0;g<N.ud;++g)if(f=N.Mc[g],f.Wc&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:M||=1282;return}e=(new e(q.buffer,d,b)).reduce((h,n)=>Math.max(h,
n))+1;break}d=0}hd(e);J.drawElements(a,b,c,d);gd&&J.bindBuffer(34962,Vc[J.Nc]);J.Oc||J.bindBuffer(34963,null)},A:a=>J.enable(a),G:a=>{N.Mc[a].enabled=!0;J.enableVertexAttribArray(a)},da:(a,b)=>{ed(a,b,"createBuffer",Vc)},Ob:(a,b)=>{ed(a,b,"createTexture",Wc)},ya:(a,b)=>{ed(a,b,"createVertexArray",Xc)},ka:(a,b)=>J.getAttribLocation(K[a],b?z(q,b):""),n:(a,b)=>nd(a,b),ib:(a,b,c,d)=>{a=J.getProgramInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,q,d,b):0;c&&(r[c>>2]=b)},M:(a,b,c)=>{if(c)if(a>=
Uc)M||=1281;else if(a=K[a],35716==b)a=J.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.ed){var d=J.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ed=Math.max(a.ed,J.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.ed}else if(35722==b){if(!a.cd)for(d=J.getProgramParameter(a,35721),b=0;b<d;++b)a.cd=Math.max(a.cd,J.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.cd}else if(35381==b){if(!a.dd)for(d=J.getProgramParameter(a,35382),b=0;b<d;++b)a.dd=Math.max(a.dd,
J.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.dd}else r[c>>2]=J.getProgramParameter(a,b);else M||=1281},jb:(a,b,c,d)=>{a=J.getShaderInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,q,d,b):0;c&&(r[c>>2]=b)},O:(a,b,c)=>{c?35716==b?(a=J.getShaderInfoLog(L[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=J.getShaderSource(L[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=J.getShaderParameter(L[a],b):M||=1281},Tb:a=>{var b=ad[a];if(!b){switch(a){case 7939:b=od(md().join(" "));
break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||(M||=1280);b=b?od(b):0;break;case 7938:b=J.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;2<=N.version&&(c=`OpenGL ES 3.0 (${b})`);b=od(c);break;case 35724:b=J.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=od(b);break;default:M||=1280}ad[a]=b}return b},X:(a,b)=>{b=b?z(q,b):"";if(a=K[a]){var c=a,d=c.Tc,e=c.Xd,f;if(!d){c.Tc=
d={};c.Wd={};var g=J.getProgramParameter(c,35718);for(f=0;f<g;++f){var h=J.getActiveUniform(c,f);var n=h.name;h=h.size;var l=pd(n);l=0<l?n.slice(0,l):n;var t=c.Cd;c.Cd+=h;e[l]=[h,t];for(n=0;n<h;++n)d[t]=n,c.Wd[t++]=l}}c=a.Tc;d=0;e=b;f=pd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Xd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||J.getUniformLocation(a,b)))return d}else M||=1281;return-1},K:a=>J.isEnabled(a),Qb:a=>(a=K[a])?J.isProgram(a):0,ua:a=>{a=K[a];J.linkProgram(a);a.Tc=0;a.Xd={}},U:(a,b)=>
{3317==a?bd=b:3314==a&&(cd=b);J.pixelStorei(a,b)},Ma:(a,b,c,d)=>J.scissor(a,b,c,d),_:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?z(q,g,d?v[d+4*f>>2]:void 0):"";e+=g}J.shaderSource(L[a],e)},Mb:(a,b,c,d,e,f,g,h,n)=>{if(2<=N.version){if(J.Xc){J.texImage2D(a,b,c,d,e,f,g,h,n);return}if(n){var l=qd(h);n>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);J.texImage2D(a,b,c,d,e,f,g,h,l,n);return}}l=n?rd(h,g,d,e,n):null;J.texImage2D(a,b,c,d,e,f,g,h,l)},T:(a,b,c)=>J.texParameteri(a,b,c),Lb:(a,b,c,d,e,f,
g,h,n)=>{if(2<=N.version){if(J.Xc){J.texSubImage2D(a,b,c,d,e,f,g,h,n);return}if(n){var l=qd(h);J.texSubImage2D(a,b,c,d,e,f,g,h,l,n>>>31-Math.clz32(l.BYTES_PER_ELEMENT));return}}n=n?rd(h,g,e,f,n):null;J.texSubImage2D(a,b,c,d,e,f,g,h,n)},gb:(a,b)=>{J.uniform1f(sd(a),b)},hb:(a,b)=>{J.uniform1i(sd(a),b)},fb:(a,b,c)=>{if(2<=N.version)b&&J.uniform3fv(sd(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=td[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+
12*b>>2);J.uniform3fv(sd(a),d)}},eb:(a,b,c,d)=>{if(2<=N.version)b&&J.uniformMatrix3fv(sd(a),!!c,w,d>>2,9*b);else{if(32>=b){b*=9;for(var e=td[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);J.uniformMatrix3fv(sd(a),!!c,e)}},sa:(a,b,c,d)=>{if(2<=N.version)b&&J.uniformMatrix4fv(sd(a),!!c,w,d>>2,
16*b);else{if(18>=b){var e=td[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var h=d+g;e[g]=f[h];e[g+1]=f[h+1];e[g+2]=f[h+2];e[g+3]=f[h+3];e[g+4]=f[h+4];e[g+5]=f[h+5];e[g+6]=f[h+6];e[g+7]=f[h+7];e[g+8]=f[h+8];e[g+9]=f[h+9];e[g+10]=f[h+10];e[g+11]=f[h+11];e[g+12]=f[h+12];e[g+13]=f[h+13];e[g+14]=f[h+14];e[g+15]=f[h+15]}}else e=w.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(sd(a),!!c,e)}},Y:a=>{a=K[a];J.useProgram(a);J.me=a},H:(a,b,c,d,e,f)=>{var g=N.Mc[a];J.Nc?(g.Wc=!1,J.vertexAttribPointer(a,b,c,!!d,
e,f)):(g.size=b,g.type=c,g.Sd=d,g.stride=e,g.wc=f,g.Wc=!0,g.be=function(h,n,l,t,u,x){this.vertexAttribPointer(h,n,l,t,u,x)})},ba:(a,b,c,d)=>J.viewport(a,b,c,d),y:()=>0,cc:(a,b,c,d)=>{var e;for(e=0;e<S.length&&null!==S[e];e++);0<e&&y("glfwCreateWindow only supports one window at time currently");var f=e+1;if(0>=a||0>=b)f=0;else{d?Fd():(P(k.canvas,a,b),Rd());for(e=0;e<S.length&&null==S[e];e++);d=k.canvas;var g=0<Cd[139265];e==S.length&&(g?Bd(d):rb());!k.ctx&&g?f=0:(a=new Sd(f,a,b,d.width,d.height,c),
f-1==S.length?S.push(a):S[f-1]=a,V=a,Ee(),f=a.id)}return f},u:()=>0,mb:a=>{a:{if(a=U(a)){a.de&&G(a.de)(a.id);S[a.id-1]=null;V.id==a.id&&(V=null);for(a of S)if(null!==a){a=void 0;break a}delete k.ctx}a=void 0}return a},Vb:()=>0,db:()=>V?V.id:0,ga:(a,b,c)=>{sa[b>>3]=Jd;sa[c>>3]=Kd},Xa:(a,b,c)=>{var d=0,e=0;if(a=U(a))d=a.Zc,e=a.Yc;b&&(r[b>>2]=d);c&&(r[c>>2]=e)},Ta:(a,b)=>{if(a=U(a)){switch(b){case 208897:a.ad[b]=xd?212995:212993}return a.ad[b]}},ac:(a,b)=>{ee();if((a=se[a])&&a.axes)return r[b>>2]=a.je,
a.axes;r[b>>2]=0},$b:(a,b)=>{ee();if((a=se[a])&&a.buttons)return r[b>>2]=a.ke,a.buttons;r[b>>2]=0},x:(a,b)=>(a=U(a))?a.keys[b]:0,Zb:(a,b,c)=>{r[b>>2]=0;r[c>>2]=0},Xb:(a,b,c,d,e)=>{r[b>>2]=0;r[c>>2]=0;r[d>>2]=screen.availWidth;r[e>>2]=screen.availHeight},_b:a=>{r[a>>2]=1;Wd||(Wd=Lc(4),r[Wd>>2]=1);return Wd},Aa:(a,b)=>(a=U(a))?0<(a.buttons&1<<b):0,Wa:()=>performance.now()/1E3-Xd,Yb:()=>0,Ua:(a,b)=>(a=U(a))?a.attributes[b]:0,qa:(a,b,c)=>{var d=0,e=0;if(a=U(a))d=a.x,e=a.y;b&&(r[b>>2]=d);c&&(r[c>>2]=e)},
Ya:(a,b,c)=>{var d=0,e=0;if(a=U(a))d=a.width,e=a.height;b&&(r[b>>2]=d);c&&(r[c>>2]=e)},ea:a=>(a=U(a))?a.$d:0,ab:()=>{if(S)return 1;Xd=performance.now()/1E3;Cd={...$d};S=[];V=null;Vd=De();window.addEventListener("gamepadconnected",fe,!0);window.addEventListener("gamepaddisconnected",ge,!0);window.addEventListener("keydown",he,!0);window.addEventListener("keypress",ce,!0);window.addEventListener("keyup",ie,!0);window.addEventListener("blur",je,!0);Yd=window.matchMedia("(resolution: "+De()+"dppx)");
Yd.addEventListener("change",Fe);var a=k.canvas;a.addEventListener("touchmove",ke,!0);a.addEventListener("touchstart",oe,!0);a.addEventListener("touchcancel",pe,!0);a.addEventListener("touchend",pe,!0);a.addEventListener("mousemove",ke,!0);a.addEventListener("mousedown",oe,!0);a.addEventListener("mouseup",pe,!0);a.addEventListener("wheel",qe,!0);a.addEventListener("mousewheel",qe,!0);a.addEventListener("mouseenter",le,!0);a.addEventListener("mouseleave",me,!0);a.addEventListener("drop",we,!0);a.addEventListener("dragover",
xe,!0);Fd=ze;Nd=Ce;P=Ae;Qd.push((b,c)=>{if(Be()){var d=k.canvas;re(d.clientWidth,d.clientHeight,b,c)}else re(b,c,b,c)});return 1},Ra:()=>0,ob:()=>0,ma:(a,b)=>{if(a=U(a)){var c=a.Vc;a.Vc=b;b=c}else b=null;return b},Wb:()=>0,bc:()=>0,oa:(a,b)=>{a=U(a);if(!a)return null;var c=a.Ic;a.Ic=b;return c},Va:()=>{},ia:(a,b)=>{if(a=U(a)){var c=a.Pc;a.Pc=b;b=c}else b=null;return b},la:a=>{var b=Td;Td=a;return b},Sa:(a,b,c)=>{if(a=U(a))switch(b){case 208897:var d=k.canvas;switch(c){case 212993:a.ad[b]=c;d.removeEventListener("click",
ye,!0);document.exitPointerLock();break;case 212994:m("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented");break;case 212995:a.ad[b]=c;d.addEventListener("click",ye,!0);d.requestPointerLock();break;default:m(`glfwSetInputMode called with unknown value parameter value: ${c}`)}break;case 208898:m("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented");break;case 208899:m("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented");break;case 208900:m("glfwSetInputMode called with GLFW_LOCK_KEY_MODS mode not implemented");
break;case 3342341:m("glfwSetInputMode called with GLFW_RAW_MOUSE_MOTION mode not implemented");break;default:m(`glfwSetInputMode called with unknown mode parameter value: ${b}`)}},na:(a,b)=>{if(a=U(a)){var c=a.bd;a.bd=b;b=c}else b=null;return b},W:a=>{var b=Ud;Ud=a;return b},ja:(a,b)=>{if(a=U(a)){var c=a.hd;a.hd=b;b=c}else b=null;return b},ha:(a,b)=>{if(a=U(a)){var c=a.jd;a.jd=b;b=c}else b=null;return b},pa:(a,b)=>{a=U(a);if(!a)return null;var c=a.fe;a.fe=b;return c},Nb:(a,b)=>{if(a=U(a))a.$d=b},
nb:()=>{},Sb:a=>{a=Math.abs(a);0==a?qc(0,0):qc(1,a)},wa:()=>{window.removeEventListener("gamepadconnected",fe,!0);window.removeEventListener("gamepaddisconnected",ge,!0);window.removeEventListener("keydown",he,!0);window.removeEventListener("keypress",ce,!0);window.removeEventListener("keyup",ie,!0);window.removeEventListener("blur",je,!0);var a=k.canvas;a.removeEventListener("touchmove",ke,!0);a.removeEventListener("touchstart",oe,!0);a.removeEventListener("touchcancel",pe,!0);a.removeEventListener("touchend",
pe,!0);a.removeEventListener("mousemove",ke,!0);a.removeEventListener("mousedown",oe,!0);a.removeEventListener("mouseup",pe,!0);a.removeEventListener("wheel",qe,!0);a.removeEventListener("mousewheel",qe,!0);a.removeEventListener("mouseenter",le,!0);a.removeEventListener("mouseleave",me,!0);a.removeEventListener("drop",we,!0);a.removeEventListener("dragover",xe,!0);Yd&&Yd.removeEventListener("change",Fe);a.width=a.height=1;V=S=null},V:(a,b)=>{Cd[a]=b},pb:a=>(a=U(a))?a.ye:0,Ca:Re,Da:Se,l:Te,c:Ue,D:Ve,
d:We,j:Xe,k:Ye,tb:Ze,B:$e,$a:af,v:bf,Ea:cf,R:df,ub:ef,S:ff,h:gf,e:hf,L:jf,z:kf,b:lf,r:mf,lb:nf,kb:of,i:pf,o:qf,ra:rf,_a:sf,bb:tf,m:uf,I:vf,Q:wf,cb:a=>a,sb:function(a,b){try{return Ya(q.subarray(a,a+b)),0}catch(c){if("undefined"==typeof dc||"ErrnoError"!==c.name)throw c;return c.zc}}};function hf(a,b){var c=X();try{G(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function We(a,b,c){var d=X();try{return G(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}
function Xe(a,b,c,d){var e=X();try{return G(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function Ue(a,b){var c=X();try{return G(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function lf(a,b,c){var d=X();try{G(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function bf(a,b,c,d,e,f,g){var h=X();try{return G(a)(b,c,d,e,f,g)}catch(n){Y(h);if(n!==n+0)throw n;Z(1,0)}}function gf(a){var b=X();try{G(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}
function pf(a,b,c,d){var e=X();try{G(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function uf(a,b,c,d,e,f,g,h){var n=X();try{G(a)(b,c,d,e,f,g,h)}catch(l){Y(n);if(l!==l+0)throw l;Z(1,0)}}function qf(a,b,c,d,e){var f=X();try{G(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}function Ve(a,b,c){var d=X();try{return G(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function nf(a,b,c,d,e){var f=X();try{G(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}
function of(a,b,c,d,e){var f=X();try{G(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}function mf(a,b,c,d){var e=X();try{G(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function kf(a,b,c){var d=X();try{G(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function jf(a,b,c,d,e){var f=X();try{G(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}function Ye(a,b,c,d,e){var f=X();try{return G(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}
function tf(a,b,c,d,e,f,g){var h=X();try{G(a)(b,c,d,e,f,g)}catch(n){Y(h);if(n!==n+0)throw n;Z(1,0)}}function af(a,b,c,d,e,f,g,h,n,l,t){var u=X();try{return G(a)(b,c,d,e,f,g,h,n,l,t)}catch(x){Y(u);if(x!==x+0)throw x;Z(1,0)}}function Te(a){var b=X();try{return G(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}function rf(a,b,c,d,e,f,g){var h=X();try{G(a)(b,c,d,e,f,g)}catch(n){Y(h);if(n!==n+0)throw n;Z(1,0)}}
function sf(a,b,c,d,e,f){var g=X();try{G(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}function $e(a,b,c,d,e,f){var g=X();try{return G(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}function ef(a){var b=X();try{return G(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0);return 0n}}function Ze(a,b,c,d,e,f){var g=X();try{return G(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}
function cf(a,b,c,d,e,f,g,h){var n=X();try{return G(a)(b,c,d,e,f,g,h)}catch(l){Y(n);if(l!==l+0)throw l;Z(1,0)}}function ff(a,b,c,d,e){var f=X();try{return G(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0);return 0n}}function Se(a,b,c,d){var e=X();try{return G(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function Re(a,b,c,d){var e=X();try{return G(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}
function df(a,b,c,d,e,f,g,h,n,l,t,u){var x=X();try{return G(a)(b,c,d,e,f,g,h,n,l,t,u)}catch(F){Y(x);if(F!==F+0)throw F;Z(1,0)}}function vf(a,b,c,d,e,f,g,h,n,l,t){var u=X();try{G(a)(b,c,d,e,f,g,h,n,l,t)}catch(x){Y(u);if(x!==x+0)throw x;Z(1,0)}}function wf(a,b,c,d,e,f,g,h,n,l,t,u,x,F,I,W){var T=X();try{G(a)(b,c,d,e,f,g,h,n,l,t,u,x,F,I,W)}catch(Q){Y(T);if(Q!==Q+0)throw Q;Z(1,0)}}
function yf(a=[]){var b=Ne;a.unshift(ea);var c=a.length,d=Ge(4*(c+1)),e=d,f;for(f of a)v[e>>2]=He(f),e+=4;v[e>>2]=0;try{var g=b(c,d);pa=g;rc(g)}catch(h){sc(h)}}
function zf(a=da){function b(){k.calledRun=!0;if(!oa){if(!k.noFSInit&&!yb){var c,d;yb=!0;c??=k.stdin;d??=k.stdout;e??=k.stderr;c?ac("/dev","stdin",c):Rb("/dev/tty","/dev/stdin");d?ac("/dev","stdout",null,d):Rb("/dev/tty","/dev/stdout");e?ac("/dev","stderr",null,e):Rb("/dev/tty1","/dev/stderr");Ub("/dev/stdin",0);Ub("/dev/stdout",1);Ub("/dev/stderr",1)}Af.ec();zb=!1;k.onRuntimeInitialized?.();k.noInitialRun||yf(a);if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var e=
k.postRun.shift();Ca.push(e)}Ba(Ca)}}if(0<Fa)Ga=zf;else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ea();Ba(Da);0<Fa?Ga=zf:k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);b()},1)):b()}}var Af;
(async function(){function a(c){c=Af=c.exports;Lc=c.gc;ve=c.hc;Ne=k._main=c.ic;Z=c.jc;Pa=c.kc;Y=c.lc;Ge=c.mc;X=c.nc;Oe=c.oc;Pe=c.pc;Qa=c.qc;Qe=c.rc;va=c.dc;Gc=c.fc;ua();Ha("wasm-instantiate");return Af}Ia("wasm-instantiate");var b={a:xf};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});wa??=k.locateFile?k.locateFile("ball_balancer.wasm",ia):ia+"ball_balancer.wasm";return a((await za(b)).instance)})();zf();
